<?php
/**
 * implemement hook_menu
 */

function cousin_vinny_menu() {

  $items = array();

  $items['admin/config/development/cousin_vinny'] = array(
    'title' => 'Cousin Vinny Configuration',
    'description' => 'Description of Cousin Vinny Configuration',
    // 'page callback' => 'drupal_get_form',
    // 'page arguments' => array('cousin_vinny_admin'),
    'access arguments' => array('administer cousin_vinny settings'),
    'type' => MENU_NORMAL_ITEM,
   );
  $items['admin/config/development/cousin_vinny/overview'] = array(
    'title' => 'Cousin Vinny imap_fetch_overview(imap_stream, sequence)',
    'description' => 'Description of Cousin Vinny Overview',
    // 'page callback' => 'drupal_get_form',
    // 'page arguments' => array('cousin_vinny_test'),
    'access arguments' => array('administer cousin_vinny settings'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
   );
  $items['admin/config/development/cousin_vinny/test'] = array(
    'title' => 'Cousin Vinny Test',
    'description' => 'Description of Cousin Vinny Test',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cousin_vinny_test'),
    'access arguments' => array('administer cousin_vinny settings'),
    'type' => MENU_LOCAL_TASK,
   );
  $items['admin/config/development/cousin_vinny/settings'] = array(
    'title' => 'Cousin Vinny Settings',
    'description' => 'Description of Cousin Vinny Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cousin_vinny_settings'),
    'access arguments' => array('administer cousin_vinny settings'),
    'type' => MENU_LOCAL_TASK,
   );

  return $items;
}

function cousin_vinny_test() {
  $form = array();

  $form['cousin_vinny_test'] = array(
    '#type' => 'textfield',
    '#title' => t('Test VIN'),
    // '#default_value' => variable_get('cousin_vinny_test_vin', 3),
    '#default_value' => 'KL1TD5DE2BB119431',
    '#size' => 25,
    '#maxlength' => 17,
    '#description' => t("The Test VIN for Cousin Vinny testing."),
    '#required' => TRUE,
  );

  return system_settings_form($form);
}

function cousin_vinny_settings() {
  $form = array();

  $form['cousin_vinny_content_type'] = array(
    '#type' => 'textfield',
    '#title' => t('Content Type'),
    // '#default_value' => variable_get('cousin_vinny_test_vin', 3),
    '#default_value' => 'Vehicle',
    '#size' => 200,
    '#maxlength' => 128,
    '#description' => t("The Content Type for Cousin Vinny."),
    '#required' => TRUE,
  );
  $form['cousin_vinny_content_edmunds_key'] = array(
    '#type' => 'textfield',
    '#title' => t('Edmunds API Key'),
    '#default_value' => variable_get('cousin_vinny_content_edmunds_key', 'hwxwzk7x36pxvtvtc8reqtrp'),
    // '#default_value' => 'hwxwzk7x36pxvtvtc8reqtrp',
    '#size' => 200,
    '#maxlength' => 128,
    '#description' => t("The API Key for Edmunds."),
    '#required' => TRUE,
  );

  return system_settings_form($form);
}

/**
 * END: Tradition Drupal Module Functionality
 */

/**
 * Example function.
 */

function _drush_execute_vin_collect($vin, $specification = 'common') {
    $buffer = '';
    $vin_is_valid = _vin_prevalidate($vin);
    if ($vin_is_valid !== TRUE) {
        $message = _vin_prevalidate($vin, TRUE);
        $buffer .= "'" . $vin . "' was the argument provided/selected to function '" . __FUNCTION__ . "'. Message: " . $message;
        drush_print($buffer);
        return;
    }
    // $json = drupal_http_request('http://maps.google.com/maps/api/geocode/json?address=1600+Amphitheatre+Parkway,+Mountain+View,+CA&sensor=false');
    // $buffer .= '$json = drupal_http_request(' . $vin . ');';
    $vin_edmunds_array = edmunds_drupalVINparser($vin);
    $vin_array = _vin_pack($vin_edmunds_array, $specification);
    $buffer .= "SPEC:\r\n=====\r\n" . print_r($specification , TRUE). "\r\n";
    $buffer .= "PACKED:\r\n=======\r\n" . print_r($vin_array , TRUE);
    $drush_dev = drush_get_option('dev',FALSE);
    if ($drush_dev) {
        $buffer .= "EDMUNDS FULL:\r\n=============\r\n" . print_r($vin_edmunds_array , TRUE);
    }
    drush_print($buffer);
    return;
}

function edmunds_drupalVINparser($vin) {
    /**
     * full from edmunds apiConsole
     * \_ http://edmunds.mashery.com/io-docs
     *
     * 'https://api.edmunds.com/api/vehicle/v2/vins/2G1FC3D33C9165616?fmt=json&api_key=hwxwzk7x36pxvtvtc8reqtrp'
     */
    $

    $dhr = '';
    $protocol = 'http'; //'https';
    $dhr .= $protocol;
    $dhr .= '://api.edmunds.com/';
    $endpoint = '/api/vehicle/v2/vins/';
    $dhr .= $endpoint;
    $dhr .= $vin;
    $dhr .= '?fmt=';
    $response_format = 'json';
    $dhr .= $response_format;
    $dhr .= '&api_key=';
    $API_key = 'hwxwzk7x36pxvtvtc8reqtrp';
    $dhr .= $API_key;

    $dhr_result = drupal_http_request($dhr);
    // $json = 'drupal_http_request('. $dhr . ')';
    $dhr_array = json_decode($dhr_result->data, TRUE);
    // $dhr_array = $dhr_result;
    // $dhr_array = $dhr;
    $dhr_array['vin'] = $vin;
    return $dhr_array;
}

    function _vin_pack($vin_edmunds_array, $specification = 'common') {
        $supported_custom_specification_array = array('acme');
        $supported_from_common_specification_array = array('common', 'vandelay','zenith');

        if (in_array($specification, $supported_from_common_specification_array)) {
            /**
             * Could be as simple as:
             *  - removing unwanted attributes for specification
             *  - renaming keys for specification
             * Could be as complex as:
             *  - changing an explicit value to a custom specification code
             *  - calculating esoteric $attributes from existing
             * However, there reaches a point where a 'custom specification' method is indicated
             *
             * @var        Function
             */
            $vin_common_array = _vin_common_pack($vin_edmunds_array);
            switch ($specification) {
                case 'common':
                    $vin_array = $vin_common_array;
                    $vin_array['specification']['name'] = $specification;
                    $vin_array['specification']['type'] = 'common';
                    $vin_array['specification']['supported'] = 'TTRUE';
                    break;
                case 'zenith':
                    $vin_array = _vin_zenithCarDealer_pack($vin_common_array);
                    break;

                default:
                    # Could Re-Write to Throw an Error, but just return common is fine for now
                    $vin_array = $vin_common_array;
                    $vin_array['specification']['name'] = $specification;
                    $vin_array['specification']['type'] = 'common';
                    $vin_array['specification']['supported'] = 'FFALSE';
                    break;
            } //END switch ($specification)
        } //END if (in_array($specification, $supported_from_common_specification_array))

        if (in_array($specification, $supported_custom_specification_array)) {
            switch ($specification) {
                case 'acme':
                    $vin_array = _vin_acmeCarDealer_pack($vin_edmunds_array);
                    break;

                default:
                    # SHOULD Re-Write to Throw an Error, but just return common is fine for now
                    $vin_array = _vin_common_pack($vin_edmunds_array);
                    $vin_array['specification']['name'] = $specification;
                    $vin_array['specification']['type'] = 'custom';
                    $vin_array['specification']['supported'] = 'FFALSE';
                    break;
            }
        } //END if (in_array($specification, $supported_custom_specification_array))

        if (!isset($vin_array['specification']['name'])) {
            # SHOULD Re-Write to Throw an Error, but just return common is fine for now
            $vin_array = _vin_common_pack($vin_edmunds_array);
            // $vin_array = array();
            $vin_array['specification']['name'] = $specification;
            $vin_array['specification']['type'] = 'none';
            $vin_array['specification']['supported'] = 'FFALSE';
        }
        return $vin_array;
    }

    function _vin_zenithCarDealer_pack($vin_packed_array = array()) {
        #\_ HOLDER for From-Common Specification Above
        #  \_ NOTE: this is too simple to be actual, but for this holder...
        // $vin_repacked_array['zenith_year'] = $vin_packed_array['year'];
        // $vin_repacked_array['zenith_make'] = $vin_packed_array['make'];
        // $vin_repacked_array['zenith_model'] = $vin_packed_array['model'];
        // $vin_repacked_array['['zenith_vin'] = $vin_packed_array['vin'];
        foreach ($vin_packed_array as $key => $value) {
            $new_key = 'zenith_' . $key;
            $vin_repacked_array[$new_key] = $value;
        }

        $vin_repacked_array['specification']['name'] = 'zenith'; //from calling?
        $vin_repacked_array['specification']['type'] = 'common'; //from calling?
        $vin_repacked_array['specification']['supported'] = 'TTRUE';

        return $vin_repacked_array;
    }

    function _vin_acmeCarDealer_pack($vin_edmunds_array = array()) {
        #\_ HOLDER for Custom Specification Above
        #  \_ NOTE: this is too simple to be actual, but for this holder...
        $vin_packed_array['acme_year'] = $vin_edmunds_array['years'][0]['year'];
        $vin_packed_array['acme_make'] = $vin_edmunds_array['make']['name'];
        $vin_packed_array['acme_model'] = $vin_edmunds_array['model']['name'];
        $vin_packed_array['acme_vin'] = $vin_edmunds_array['vin'];

        $vin_packed_array['specification']['name'] = 'acme'; //from calling?
        $vin_packed_array['specification']['type'] = 'custom'; //from calling?
        $vin_packed_array['specification']['supported'] = 'TTRUE';

        return $vin_packed_array;
    }

    function _vin_common_pack($vin_edmunds_array = array()) {
        $vin_packed_array['vin'] = $vin_edmunds_array['vin'];
        $vin_packed_array['year'] = $vin_edmunds_array['years'][0]['year'];
        $vin_packed_array['make'] = $vin_edmunds_array['make']['name'];
        $vin_packed_array['model'] = $vin_edmunds_array['model']['name'];

        $engine_size = $vin_edmunds_array['engine']['size'];
        $engine_displacement = $vin_edmunds_array['engine']['displacement'];
        if ($engine_size + $engine_displacement + 0 > 0) {
            $vin_packed_array['engine-size'] = $engine_size;
            $vin_packed_array['engine-displacement'] = $engine_displacement;
            $engine_displacement = $engine_displacement + 0 > 0 ? $engine_displacement . 'CC ' : '';
            $engine_size = $engine_size + 0 > 0 ? $engine_size . 'L ' : '';
            $engine = trim($engine_size . $engine_displacement);
            $vin_packed_array['engine'] = $engine;
        }

        $drive = explode(' ', $vin_edmunds_array['drivenWheels']);
        foreach ($drive as $key => $word) {
            $word = $word == 'four' ? '4' : $word;
            $drive[$key] = strtoupper(substr($word, 0, 1));
        }
        $vin_packed_array['drive'] = implode('', $drive);

        $vin_packed_array['transmission'] = ucwords(strtolower($vin_edmunds_array['transmission']['transmissionType']));
        $vin_packed_array['doors'] = $vin_edmunds_array['numOfDoors'];
        $vin_packed_array['mpg-hwy'] = $vin_edmunds_array['MPG']['highway'];
        $vin_packed_array['mpg-city'] = $vin_edmunds_array['MPG']['city'];

        $vin_packed_array['fuel'] = $vin_edmunds_array['engine']['type'];
        $vin_packed_array['fuel-type'] = $vin_edmunds_array['engine']['fuelType'];

        /*<categories>*/
        $vin_packed_array['epa-class'] = $vin_edmunds_array['categories']['EPAClass'];
        $vin_packed_array['vehicle-size'] = $vin_edmunds_array['categories']['vehicleSize'];
        $vin_packed_array['primary-body-type'] = $vin_edmunds_array['categories']['primaryBodyType'];
        $vin_packed_array['vehicle-style'] = $vin_edmunds_array['categories']['vehicleStyle'];
        $vin_packed_array['vehicle-type'] = $vin_edmunds_array['categories']['vehicleType'];
        /*</categories>*/
        /*<years-styles-submodel-modelName>*/
        $vin_packed_array['model-name'] = $vin_edmunds_array['years'][0]['styles'][0]['submodel']['modelName'];
        $vin_packed_array['model-descr'] = $vin_edmunds_array['years'][0]['styles'][0]['name'];
        /*</years-styles-submodel-modelName>*/

        return $vin_packed_array;
    }

    function _vin_prevalidate(&$vin, $mssg_return = FALSE){
    $vin = strtoupper($vin);
    $error_array = array();
    if (strlen($vin) !== 17) {
        $error_array[] = 'expected Lengh of 17 not met [' . strlen($vin) . ']';
    }
    if (!ctype_alnum($vin)) {
        $error_array[] = 'one or more non-AlphNum characters';
    }
    $vin_check = 'X' . $vin;
    $vin_ioq = strpos($vin_check, 'I') + strpos($vin_check, 'O') + strpos($vin_check, 'Q') + 0;
    if ($vin_ioq > 0) {
        $error_array[] = "one or more of invalid characters ['I','O','Q']";
    }

    if (count($error_array) > 0) {
        $is_valid = FALSE;
        $message = 'Value does NOT meet common criteria of a VIN: ';
        $message .= implode('; ', $error_array) . '.';
    }else{
        $is_valid = TRUE;
        $message = 'Value meets common criteria of a VIN.';
    }
    if ($mssg_return) {
        return $message;
    }else{
        return $is_valid;
    }
}

function _query_nid_array() {
    $build_query_dbtng['main'] = "select nid from node";
    $build_query_dbtng['where'] = "1 = 1";
    $build_query_dbtng['limit'] = $arg == 'list' ? 1 : '';
    $build_query_dbtng['orderby'] = 'nid';
    $build_query_dbtng['direction'] = 'ASC';
    $build_query_dbtng['aggregate'] = '';

    if ($option['count'] + 0 > 0) {
        $limit = $option['count'] + 0;
        $build_query_dbtng['limit'] = 'LIMIT ' . $limit;
    }
    if (strlen($option['orderby'])) {
        #\_ would normally validate, but too much for demo
        $build_query_dbtng['orderby'] = 'ORDER BY ' . $option['orderby'];
    }
    if ($option['orderby-desc']) {
        $build_query_dbtng['direction'] = 'DESC';
    }
    if (strlen($option['content-types'])) {
        #\_ would normally validate and implode, but too much for demo
        $build_query_dbtng['where'] = 'WHERE content_type = ' . $option['content-types'];
    }
    if ($argument == 'groupby') {
        #\_ no options for demo
        $build_query_dbtng['aggregate'] = 'GROUP BY content_type';
    }
    if ($argument == 'cube') {
        #\_ no options for demo
        $build_query_dbtng['aggregate'] = 'CUBE content_type';
    }
}